XRTK.Lumin/Packages/com.xrtk.lumin/Inspectors/LuminSpatialMeshObserverProfileInspector.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Inspectors/LuminSpatialMeshObserverProfileInspector.cs.meta, XRTK.Lumin/Packages/com.xrtk.lumin/LuminApi.cs, XRTK.Lumin/Packages/com.xrtk.lumin/LuminApi.cs.meta, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles/LuminSpatialMeshObserverProfile.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles/LuminSpatialMeshObserverProfile.cs.meta, XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminApi.cs, XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminApi.cs.meta, XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminSpatialMeshObserver.cs, XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminSpatialMeshObserver.cs.meta, XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/placeholder.txt.meta, XRTK.Lumin/Packages/com.xrtk.lumin/XRTK.Lumin.asmdef
Implements the spatial observers for Lumin
- Fixes: #3
=> Dev spatial awareness

XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminSpatialMeshObserver.cs
Finishes https://github.com/XRTK/XRTK-Core/pull/179
=> added the collider option

XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminSpatialMeshObserver.cs
Fixed editor crash in play mode with spatial mesh observer, we now wait until the mesh subsystem is running
=> Fixed editor crash with Lumin Spatial Observer in playmode

XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminController.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminControllerDataProvider.cs, XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminSpatialMeshObserver.cs
Made sure touchpad data resets after use.
Fixed some exceptions from the mesh subsystem.
=> Misc Bug Fixes

XRTK.Lumin/Packages/com.xrtk.lumin/Inspectors/XRTK.Lumin.Inspectors.asmdef, XRTK.Lumin/Packages/com.xrtk.lumin/XRTK.Lumin.asmdef
updated assembly defs to use guids
=> updated assembly defs to use guids

XRTK.Lumin/Packages/com.xrtk.lumin/SpatialObservers/LuminSpatialMeshObserver.cs, XRTK.Lumin/Packages/com.xrtk.lumin/package.json, XRTK.Lumin/Packages/manifest.json
* updated the usages of camera cache main if the camera rig's camera reference
* bumped versions
=> Release 0.1.8

XRTK.Lumin/Packages/com.xrtk.lumin/Inspectors/LuminSpatialMeshObserverProfileInspector.cs.meta
=> fixed missing icon

XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminController.cs
Fixed inverted axis events
Related to https://github.com/XRTK/XRTK-Core/pull/415
=> fixed inverted axis events

XRTK.Lumin/Packages/com.xrtk.lumin/Inspectors/LuminMotionControllerMappingProfileInspector.cs, XRTK.Lumin/Packages/com.xrtk.lumin/package.json, XRTK.Lumin/Packages/manifest.json
https://github.com/XRTK/XRTK-Core/pull/418
=> updated lumin profile inspector with updated namespace

XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/Hands/LuminHandControllerDataProvider.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Inspectors/LuminHandControllerDataProviderProfileInspector.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles/LuminHandControllerDataProviderProfile.cs
Continued from https://github.com/XRTK/XRTK-Core/pull/476
=> update lumin hand controller data provider

XRTK.Lumin/Packages/com.xrtk.lumin/LuminPlatform.cs, XRTK.Lumin/Packages/com.xrtk.lumin/LuminPlatform.cs.meta, XRTK.Lumin/Packages/com.xrtk.lumin/package.json, XRTK.Lumin/Packages/manifest.json
Continued from https://github.com/XRTK/XRTK-Core/pull/416
=> added lumin platform definition

XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminController.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminControllerDataProvider.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminHandControllerDataProvider.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Utilities/LuminHandDataConverter.cs
- https://github.com/XRTK/XRTK-Core/pull/501
- updated palm pose
=> Fixed lumin hand controller support

XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminController.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Controllers/LuminControllerDataProvider.cs
https://github.com/XRTK/XRTK-Core/pull/505
=> added controller data provider reference to the controller

XRTK.Lumin/Packages/com.xrtk.lumin/LuminPlatform.cs
https://github.com/XRTK/XRTK-Core/pull/518
=> updated platform flag to only be true on device

XRTK.Lumin/Packages/com.xrtk.lumin/LuminPlatform.cs
https://github.com/XRTK/XRTK-Core/pull/521
=> updated lumin platform definition

XRTK.Lumin/Packages/com.xrtk.lumin/Inspectors/LuminHandControllerDataProviderProfileInspector.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles/LuminHandControllerDataProviderProfile.cs
Companion PR to https://github.com/XRTK/XRTK-Core/pull/526
=> Change requests for controller provider inspectors

XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/LuminPlatform.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/Providers/CameraSystem/LuminCameraDataProvider.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/Providers/Controllers/LuminController.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/Providers/Controllers/LuminControllerDataProvider.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/Providers/Controllers/LuminHandControllerDataProvider.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/Providers/SpatialAwarenessSystem/SpatialObservers/LuminSpatialMeshObserver.cs
https://github.com/XRTK/XRTK-Core/pull/551
=> added guid references to all instanced types

XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/CameraSystem/LuminCameraDataProvider.asset
=> fixed reference to camera rig

.gitignore, XRTK.Lumin/Assets/XRTK.Generated.meta, XRTK.Lumin/Assets/XRTK.Generated/Lumin.meta, XRTK.Lumin/Assets/XRTK.Generated/SymbolicLinkSettings.asset, XRTK.Lumin/Assets/XRTK.Generated/SymbolicLinkSettings.asset.meta, XRTK.Lumin/Packages/com.xrtk.lumin/package.json, XRTK.Lumin/Packages/manifest.json, azure-pipelines.yml, azure_pipelines/common.yml, azure_pipelines/stages/publish.yml, azure_pipelines/stages/steps/build-docs.yml, azure_pipelines/stages/steps/build-unity-player.yml, azure_pipelines/stages/steps/export-package-seed.yml, azure_pipelines/stages/steps/install-unity.yml, azure_pipelines/stages/steps/return-unity-license.yml, azure_pipelines/stages/steps/run-unity-tests.yml, azure_pipelines/stages/steps/upm-package-info.yml, azure_pipelines/stages/unity-build.yml
Modernized the package with core dependency and azure pipelines
- added preview core package dep
- added azure pipelines yaml
=> Added preview package capabilities

XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/Controllers/LuminControllerDataProviderProfile.asset
Fixed the missing controller mappings
=> fixed broken controller mapping

azure_pipelines/stages/publish.yml, azure_pipelines/stages/steps/build-unity-player.yml, azure_pipelines/stages/steps/export-package-seed.yml, azure_pipelines/stages/steps/install-unity.yml, azure_pipelines/stages/steps/return-unity-license.yml, azure_pipelines/stages/steps/run-unity-tests.yml, azure_pipelines/stages/steps/upm-package-info.yml, azure_pipelines/stages/unity-build.yml
=> sync pipeline changes

XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/Providers/Controllers/LuminHandControllerDataProvider.cs
Fixed some compiler errors introduced by the now merged changes for Hands Core implementation.
=> Fix compiler errors in LuminHandControllerDataProvider

XRTK.Lumin/Packages/manifest.json, azure_pipelines/stages/steps/install-unity.yml
fixes unity module installation
=> fix unity module installation

XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/Controllers/Left/TouchpadPressProfile.asset, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/Controllers/Right/TouchpadPressProfile.asset
https://github.com/XRTK/SDK/pull/212
=> Clean up grip related input actions

XRTK.Lumin/Packages/com.xrtk.lumin/Editor/BuildPipeline/LuminBuildInfo.cs
Removed logs when building
- https://github.com/XRTK/XRTK-Core/pull/836
=> cleaned up build info logs

XRTK.Lumin/Packages/com.xrtk.lumin/Editor/AssemblyInfo.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Editor/AssemblyInfo.cs.meta, XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/AssemblyInfo.cs, XRTK.Lumin/Packages/com.xrtk.lumin/Runtime/AssemblyInfo.cs.meta
Adding compiler definitions for platforms
- https://github.com/XRTK/XRTK-Core/pull/839
=> Adding compiler definitions for platforms

XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/LuminPlatformServiceConfigurationsProfile.asset, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/SpatialAwarenessSystem.meta, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/SpatialAwarenessSystem/LuminSpatialMeshObserverProfile.asset, XRTK.Lumin/Packages/com.xrtk.lumin/Profiles~/SpatialAwarenessSystem/LuminSpatialMeshObserverProfile.asset.meta
added lumin spatial mesh observer profile
- https://github.com/XRTK/XRTK-Core/pull/848
=> added lumin spatial mesh observer profile
